# ==========================================================
# Ambiente LOCAL (dev) — PostgreSQL no Docker (localhost:5434)
# ==========================================================
spring.datasource.url=jdbc:postgresql://localhost:5434/eventostec
spring.datasource.username=postgres
spring.datasource.password=postgres
